"""add task start_date and comment attachments

This is the actual feature migration for this update:
  - task.start_date (nullable Date) - old rows get NULL, no data loss,
    no default guessed on their behalf.
  - comment_attachment table - new, so nothing to migrate into it.

Safe on both fresh and existing databases; see 0001's docstring for
the exact commands existing installs need to run first.

Revision ID: a3b78a406719
Revises: 0b003ebbc203
Create Date: 2026-08-17 10:33:54.014601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3b78a406719'
down_revision = '0b003ebbc203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('start_date')

    op.drop_table('comment_attachment')
    # ### end Alembic commands ###
